Exams/urls.py
from django.urls import path
from .views import create_exam, takeTheExams, ListExams, checkAnswers, Manage, Search, Random, checkRandom
from django.conf import settings
from django.conf.urls.static import static

app_name = 'exam'
urlpatterns = [
    path('create/', create_exam.as_view(), name='create-exam'),
    path('list/', ListExams.as_view(), name='show-list-exam'),
    path('do/<str:nameExam>/', takeTheExams.as_view(), name='do-exam'),
    path('do/score', checkAnswers.as_view(), name='check'),
    path('random/score', checkRandom.as_view(), name='check_random'),
    path('manageExams/', Manage.as_view(), name='manage'),
    path('random', Random.as_view(), name='getRandom'),
    path('list/search', Search.as_view(), name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

History/urls.py
from django.urls import path
from .views import HistoryView, View_exam

app_name = 'history'
urlpatterns = [
    path('', HistoryView.as_view(), name='getHistory'),
    path('history/<id_history>/', View_exam.as_view(), name='show_history')
]

Home/urls.py
from django.urls import path
from .views import Index
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Home'
urlpatterns = [
    path('', Index.as_view(), name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyUser/urls.py
from django.urls import path
from .views import Login, Signup, Ajax, Info, Logout, forgotpass
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myuser'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('signup/', Signup.as_view(), name='signup'),
    path('info/', Info.as_view(), name='info'),
    path('forgotpass', forgotpass, name='forgot'),
    path('logout', Logout.as_view(), name='logout'),

    path('ajax/', Ajax.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thiOnline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
    path('dethi/', include('Exams.urls')),
    path('user/', include("MyUser.urls")),
    path('history/', include("History.urls")),
]

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

# Create your views here.


class Index(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request):
        return redirect('exam:show-list-exam')

Home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'Home/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static 'Home/javascript/style.js' %}"></script>

</head>
<body>
<div id="header">
    <div class="header-left">
        <span class="control-menu"><img src="{% static 'Home/images/menu.png' %}"></span>
        <a href="{% url 'Home:home' %}"><img src="{% static 'Home/images/logo.png' %}" class="logo-web"></a>
    </div>
    <div class="header-right">
        {% if user.is_authenticated %}
        <div>
            <a class="btn-login avatar-user" href="{% url 'myuser:info' %}"><img src="{{ MEDIA_URL }}{{ user.image }}"></a>
        </div>

        {% else %}
        <a class="btn-login" href="{% url 'myuser:login' %}">Log in</a><span> | </span>
        <a class="btn-signup" href="{% url 'myuser:signup' %}">Sign up</a>
        {% endif %}
    </div>
</div>
<div id="content">
    <div class="menu-left">
        <div class="icon-left test">
            <a href="{% url 'exam:show-list-exam' %}">
                <span><img src="{% static 'Home/images/test.png' %}" alt="Luyện tập" title="Luyện tập"></span>
                <span class="content-icon-left">Luyện tập</span>
            </a>
        </div>

        <div class="icon-left create-exam">
            <a href="{% url 'exam:create-exam' %}">
                <span><img src="{% static 'Home/images/create.png' %}" alt="Tạo đề" title="Tạo đề"></span>
                <span class="content-icon-left">Tạo đề</span>
            </a>
        </div>


        <div class="icon-left history">
            <a href="{% url 'history:getHistory' %}">
                <span><img src="{% static 'Home/images/history.png' %}" alt="Lịch sử" title="Lịch sử"></span>
                <span class="content-icon-left">Lịch sử</span>
            </a>
        </div>
        <div class="icon-left manage-exam">
            <a href="{% url 'exam:manage' %}">
                <span><img src="{% static 'Home/images/manage.png' %}" alt="Quản lý đề" title="Quản lý đề"></span>
                <span class="content-icon-left">Quản lý đề</span>
            </a>
        </div>
        <div class="icon-left settings">
            <a href="{% url 'exam:create-exam' %}">
                <span><img src="{% static 'Home/images/settings.png' %}" alt="Cài đặt" title="Cài đặt"></span>
                <span class="content-icon-left">Cài đặt</span>
            </a>
        </div>
    </div>
    <div class="content-center">
        {% block content %}
        {% endblock %}

    </div>
</div>

</body>
</html>