Exams/urls.py
from django.urls import path
from .views import create_exam, takeTheExams, ListExams, checkAnswers, Manage, Search, Random, checkRandom
from django.conf import settings
from django.conf.urls.static import static

app_name = 'exam'
urlpatterns = [
    path('create/', create_exam.as_view(), name='create-exam'),
    path('list/', ListExams.as_view(), name='show-list-exam'),
    path('do/<str:nameExam>/', takeTheExams.as_view(), name='do-exam'),
    path('do/score', checkAnswers.as_view(), name='check'),
    path('random/score', checkRandom.as_view(), name='check_random'),
    path('manageExams/', Manage.as_view(), name='manage'),
    path('random', Random.as_view(), name='getRandom'),
    path('list/search', Search.as_view(), name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

History/urls.py
from django.urls import path
from .views import HistoryView, View_exam

app_name = 'history'
urlpatterns = [
    path('', HistoryView.as_view(), name='getHistory'),
    path('history/<id_history>/', View_exam.as_view(), name='show_history')
]

Home/urls.py
from django.urls import path
from .views import Index
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Home'
urlpatterns = [
    path('', Index.as_view(), name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thiOnline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
    path('dethi/', include('Exams.urls')),
    path('user/', include("MyUser.urls")),
    path('history/', include("History.urls")),
]

Exams/models.py
from djongo import models
from MyUser.models import User
# Create your models here.
#
class Exams(models.Model):
    name = models.CharField(max_length=255, null=False)
    slug = models.CharField(max_length=255, null=False)
    innitiated_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    id_author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, null=False)
    level_of_different = models.FloatField(default=2.5)
    medium_score = models.FloatField(default=0)
    time = models.IntegerField(null=False)
    list_id_questions = models.TextField(null=True)
    list_id_questions_group = models.TextField(null=True, blank=True)
    amount_questions = models.IntegerField(null=False, default=0)
    amount_view_user = models.IntegerField(default=0)
    amount_do = models.IntegerField(default=0)
    comments = models.JSONField(null=True, blank=True, default=dict)
    options = models.JSONField(null=True, blank=True, default=dict)

Exams/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import View
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Exams
from Questions.models import Questions
from History.models import History
import unidecode
import re
from django.core.paginator import Paginator
import random


class create_exam(LoginRequiredMixin, View):
    login_url = '/user/login/'
    list_subject = ['Toán', 'Lý', 'Hoá', 'Sinh', 'Sử', 'Địa', 'Công dân', 'Tiếng anh']

    def get(self, request):
        return render(request, 'Exams/create_exam.html', {'subjects': self.list_subject})

    def post(self, request):
        message = ''
        alphabet = 'ABCD'
        name = request.POST['name_exam']
        if name == '':
            message = 'Tên đề không được để trống'
            return render(request, 'Exams/create_exam.html', {'message': message})
        subject = request.POST['subject']
        time = request.POST['time']
        if int(time) < 10 or int(time) > 300:
            message = 'Thời gian làm bài không nhỏ hơn 10 phút và lớn hơn 30 phút'
            return render(request, 'Exams/create_exam.html', {'message': message})
        us = request.user

        exam = Exams.objects.create(
            name=name,
            slug=re.sub(r'[ ]+', '-', unidecode.unidecode(name)),
            subject=subject,
            time=time,
            id_author=us
        )
        if us.list_id_exam != None:
            us.list_id_exam = us.list_id_exam + " " + str(exam.id)
        else:
            us.list_id_exam = str(exam.id)
        us.save()
        list_id_questions = []
        i = 1
        while (True):
            try:
                question = request.POST['question-' + str(i)]
                level = request.POST['level-' + str(i)]
                if question == '':
                    break
                id_exam = exam
                try:
                    correct_answer = request.POST['correct-answer-' + str(i)]

                except:
                    Exams.objects.remove(exam)
                    message = 'Vui lòng nhập đáp án đúng'
                    return render(request, 'Exams/create_exam.html', {'message': message})
                answers = []
                for alpha in alphabet:
                    try:
                        status = False
                        content = request.POST['answer-' + alpha + '-' + str(i)]
                        if content.strip() == '':
                            Exams.objects.remove(exam)
                            message = 'Câu trả lời không được bỏ trống'
                            return render(request, 'Exams/create_exam.html', {'message': message})
                        if correct_answer == alpha:
                            status = True
                        label = alpha
                        answer = {
                            'content': content,
                            'status': status,
                            'label': label,
                        }
                        answer = json.loads(json.dumps(answer))
                        answers.append(answer)
                    except:
                        pass
                try:
                    link_media = request.FILES['image-' + str(i)]
                except:
                    link_media = ''
                i = i + 1
                q = Questions.objects.create(
                    level_of_different=level,
                    id_exam=exam,
                    question=question,
                    answers=answers,
                    subject=subject,
                    link_media=link_media,
                    correct_answer=correct_answer
                )
                list_id_questions.append(q.id)

            except:
                break
        exam.list_id_questions = list_id_questions
        exam.amount_questions = len(list_id_questions)
        exam.save()

        return redirect('exam:show-list-exam')


class Search(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request):
        str_search = request.GET['search']
        print(str_search)
        exams = Exams.objects.filter(name__icontains=str_search)
        paginator = Paginator(exams, 5)  # Show 25 contacts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'Exams/listExam.html', {'exams': page_obj})


class ListExams(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request):
        exams = Exams.objects.all().order_by('-innitiated_date')
        paginator = Paginator(exams, 5)  # Show 25 contacts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'Exams/listExam.html', {'exams': page_obj})


class takeTheExams(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request, nameExam):
        id_exam = str(request.GET['check']).split('-')[-1]
        exam = Exams.objects.get(id=id_exam)
        questions = exam.questions_set.all()
        exam.amount_view_user = exam.amount_view_user + 1
        exam.save()
        number = len(questions)
        return render(request, 'Exams/do_exam.html', {
            'exam': exam,
            'questions': questions,
            'number': number,
        })


class checkAnswers(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def post(self, request):
        id_exam = request.POST['id']
        exam = Exams.objects.get(id=id_exam)
        exam.amount_do = exam.amount_do + 1
        exam.save()
        questions = exam.questions_set.all()
        id_list_questions = ''
        list_user_answer = ''
        user = request.user
        time_do = request.POST['time-do']
        scores = 0
        for question in questions:
            id_list_questions = id_list_questions + " " + str(question.id)
            try:
                answer = request.POST[str(question.id)]
                question.correct = answer
                if answer == question.correct_answer:
                    scores = scores + 1
            except:
                question.correct = None
            list_user_answer = list_user_answer + " " + str(question.correct)

        h = History.objects.create(
            id_exam=exam,
            time_do=time_do,
            id_user=user,
            list_user_answers=list_user_answer,
            id_list_questions=id_list_questions,
            correct=scores
        )
        if user.list_id_history != None:
            user.list_id_history = user.list_id_history + " " + str(h.id)
        else:
            user.list_id_history = h.id
        user.save()
        number = len(questions)
        return render(request, 'Exams/test_results.html', {
            'exam': exam,
            'questions': questions,
            'number': number,
            'score': scores
        })


class Manage(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request):
        user = request.user
        all_exams_do = History.objects.filter(id_user=user)
        exams_do = []
        for e in all_exams_do:
            if e.id_exam not in exams_do:
                exams_do.append(e)

        exams_create = Exams.objects.filter(id_author=user)
        return render(request, 'Exams/manage.html', {
            'exams_do': exams_do,
            'exams_create': exams_create,

        })


class Random(LoginRequiredMixin, View):
    login_url = '/user/login/'
    list_subject = ['Toán', 'Lý', 'Hoá', 'Sinh', 'Sử', 'Địa', 'Công dân', 'Tiếng anh']
    levels = ['Rất dễ', 'Dễ', 'Trung bình', 'Khó', 'Rất khó']

    def get(self, request):
        return render(request, 'Exams/form_random.html', {'list_subject': self.list_subject, 'levels': self.levels})

    def post(self, request):
        subject = request.POST['subject']
        level1 = request.POST['r-1']
        level2 = request.POST['r-2']
        level3 = request.POST['r-3']
        level4 = request.POST['r-4']
        level5 = request.POST['r-5']
        time = request.POST['time']
        questions = Questions.objects.all()
        questions_level1 = []
        questions_level2 = []
        questions_level3 = []
        questions_level4 = []
        questions_level5 = []
        for q in questions:
            if q.subject == subject:
                if q.level_of_different == 1:
                    questions_level1.append(q)
                elif q.level_of_different == 2:
                    questions_level2.append(q)
                elif q.level_of_different == 3:
                    questions_level3.append(q)
                elif q.level_of_different == 4:
                    questions_level4.append(q)
                elif q.level_of_different == 5:
                    questions_level5.append(q)
            else:
                pass

        random.shuffle(questions_level1)
        random.shuffle(questions_level2)
        random.shuffle(questions_level3)
        random.shuffle(questions_level4)
        random.shuffle(questions_level5)

        if len(questions_level1) < int(level1) or len(questions_level2) < int(level2) or len(
                questions_level3) < int(level3) or len(questions_level4) < int(level4) or len(questions_level5) < int(level5):
            return render(request, 'Exams/form_random.html',
                          {'list_subject': self.list_subject, 'levels': self.levels,
                           'message': 'Không đủ câu hỏi theo yêu cầu!'})
        questions = questions_level1[:int(level1)] + questions_level2[:int(level2)] + questions_level3[:int(
            level3)] + questions_level4[:int(level4)] + questions_level5[:int(level5)]
        return render(request, 'Exams/show_random.html', {
            'questions': questions,
            'time': int(time),

Exams/templates/Exams/create_exam.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Exams/css/create_exam.css' %}">
<script src="{% static 'Exams/javascript/create_exam.js' %}"></script>
<div class="wrapper-create-exam">
    <form action="{% url 'exam:create-exam' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if message %}
        <div class="error">{{ message }}</div>
        {% endif %}

        <div class="create-exam">
            <div class="button-exam">
                <button type="button" class="btn-exam active-exam" id="info info-exam">Đề thi</button>
                <button type="button" class="btn-exam" id="info info-options">Tuỳ chọn</button>
            </div>
            <div class="info info-exam">
                <div>
                    <label for="name-exam">Tên đề: </label>
                    <input type="text" name="name_exam" id="name-exam">
                </div>
                <div>
                    <div>
                        <label for="subject">Môn: </label>
                        <select name="subject" id="subject">
                            {% for subject in subjects %}
                            <option value="{{ subject }}">{{ subject }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <label for="time">Thời gian: </label>
                        <input type="number" name="time" id="time" min="5" max="300" value="50"><span> Phút</span>
                    </div>
                </div>
            </div>
            <div class="info info-options" style="display:none;">
                <span>info options</span>
            </div>
        </div>
        <div class="create-questions">
            <div class="wrapper">
                {% for i in "x"|rjust:"5" %}
                <div class="info-question">
                    <div class="line">
                        <label for="question">Câu {{ forloop.counter }}: </label>
                        <textarea name="question-{{ forloop.counter }}" id="question" rows="3"></textarea>
                    </div>
                    <div class="line">
                        <input type="file" name="image-{{ forloop.counter }}" id="image-exam"
                               accept="image/png, image/jpeg">
                    </div>
                    <div class="line answers">
                        <div style="font-size: 1.2rem;"> Đáp án:</div>
                        <div class="answer">
                            <label for="A-{{ forloop.counter }}">A: </label>
                            <input type="text" name="answer-A-{{ forloop.counter }}" id="A-{{ forloop.counter }}">
                        </div>
                        <div class="answer">
                            <label for="B-{{ forloop.counter }}">B: </label>
                            <input type="text" name="answer-B-{{ forloop.counter }}" id="B-{{ forloop.counter }}">
                        </div>
                        <div class="answer">
                            <label for="C-{{ forloop.counter }}">C: </label>
                            <input type="text" name="answer-C-{{ forloop.counter }}" id="C-{{ forloop.counter }}">
                        </div>
                        <div class="answer">
                            <label for="D-{{ forloop.counter }}">D: </label>
                            <input type="text" name="answer-D-{{ forloop.counter }}" id="D-{{ forloop.counter }}">
                        </div>
                    </div>
                    <div class="line correct-answer">
                        <div style="margin-bottom: 2rem">
                            Đáp án đúng?
                        </div>
                        <div>
                            <label for="A-{{ forloop.counter }}-radio">A: </label>
                            <input type="radio" name="correct-answer-{{ forloop.counter }}"
                                   id="A-{{ forloop.counter }}-radio" value="A">
                            <label for="B-{{ forloop.counter }}-radio">B: </label>
                            <input type="radio" name="correct-answer-{{ forloop.counter }}"
                                   id="B-{{ forloop.counter }}-radio" value="B">
                            <label for="C-{{ forloop.counter }}-radio">C: </label>
                            <input type="radio" name="correct-answer-{{ forloop.counter }}"
                                   id="C-{{ forloop.counter }}-radio" value="C">
                            <label for="D-{{ forloop.counter }}-radio">D: </label>
                            <input type="radio" name="correct-answer-{{ forloop.counter }}"
                                   id="D-{{ forloop.counter }}-radio" value="D">
                        </div>
                    </div>
                    <div class="level">
                        <label for="level">Độ khó:</label>
                        <select name="level-{{ forloop.counter }}" id="level">
                            <option value="1">Rất dễ</option>
                            <option value="2">Dễ</option>
                            <option value="3" selected>Trung bình</option>
                            <option value="4">Khó</option>
                            <option value="4">Rất khó</option>
                        </select>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="add-remove-question">
                <span class="add-question"><img src="{% static 'Exams/image/plus.png' %}" alt=""></span>
                <span class="remove-question"><img src="{% static 'Exams/image/remove.png' %}" alt=""></span>
            </div>
        </div>
        <div class="submit">
            <button type="submit" class="submit-exam">Xong</button>
        </div>
    </form>
</div>
{% endblock %}

Exams/templates/Exams/do_exam.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Exams/css/do_exam.css' %}">
<script src="{% static 'Exams/javascript/do_exam.js' %}"></script>
<form action="{% url 'exam:check' %}" method="post" id="form-submit">
    {% csrf_token %}
    <input type="hidden" name="do-time" value="{{ exam.time }}" id="do-time">
    <div class="wrapper-exam">
        <div class="show-exam">
            <div class="info-exam">
                <h2 class="title-exam">{{ exam.name }}</h2>
                <div class="time">Thời gian: {{ exam.time }}</div>
            </div>
            <div class="questions">
                {% for question in questions %}
                <div class="question">
                    <div class="title-qs">
                        <span>{{ forloop.counter }}. </span>{{ question.question }}
                        <div>
                            {% if question.link_media %}
                            <center><img src="{{ MEDIA_URL }}{{ question.link_media }}" width="50%"></center>
                            {% endif %}
                        </div>
                    </div>
                    {% with my_var=forloop.counter %}


                    {% for answer in question.answers %}
                    <div>
                        <span>{{ answer.label }}: </span>
                        <input type="radio" id="{{ my_var }}" name="{{ question.id }}"
                               value="{{ answer.label }}">
                        <label for="{{ my_var }}">{{ answer.content }}</label><br>
                    </div>
                    {% endfor %}
                    {% endwith %}
                </div>
                {% endfor %}
            </div>
            <div class="wrapper-submit">
                <input type="hidden" name="time-do" value="0">
                <input type="hidden" name="id" value="{{ exam.id }}">
                <button type="submit" class="submit">Nộp bài</button>
            </div>
        </div>
        <div class="check-questions">
            <div id="clock">
                <span id="h">Giờ</span> :
                <span id="m">Phút</span> :
                <span id="s">Giây</span>
            </div>
            <div class="form-check">
                {% for i in questions %}
                <div class="qs qs-{{ forloop.counter }}">{{ forloop.counter }}</div>
                {% endfor %}
            </div>
        </div>

    </div>

</form>
{% endblock %}

Exams/templates/Exams/form_random.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Exams/css/random.css' %}">
<div class="wrapper-random">
    <form action="{% url 'exam:getRandom' %}" method="post">
        {% csrf_token %}
        {% if message %}
            <div style="color: red">{{ message }}</div>
        {% endif %}
        <div class="subject">
            <label for="subject">Môn: </label>
            <select name="subject" id="subject">
                {% for subject in list_subject %}
                <option value="{{ subject }}">{{ subject }}</option>
                {% endfor %}
            </select>
            </select>
        </div>
        <div class="level">
            {% for level in levels %}
            <div>
                <label for="r-{{ forloop.counter }}">{{ level }}: </label>
                <input type="number" name="r-{{ forloop.counter }}" id="r-{{ forloop.counter }}" value="1"> Câu
            </div>
            {% endfor %}
        </div>
        <div>
            <label for="time">Thời gian: </label>
            <input type="number" id="time" value="50" name="time"> Phút
        </div>
        <div class="submit">
            <button type="submit">Tạo</button>
        </div>

    </form>
</div>

{% endblock %}

Exams/templates/Exams/listExam.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Exams/css/list_exams.css' %}">
<div>
    <div class="find">
        <div>
            <span>Sắp xếp theo: </span>
            <select name="filters" id="filters">
                <option value="Phổ biến">Phổ biến</option>
                <option value="Mới">Mới</option>
            </select>
        </div>
        <div class="random-exam">
            <a href="{% url 'exam:getRandom' %}">Tạo đề ngẫu nhiên</a>
        </div>
        <div class="search">
            <form action="{% url 'exam:search' %}" method="get">
                {% csrf_token %}
                <input type="text" name="search" id="searchbar" placeholder="Search">

            </form>
        </div>
    </div>
    <div class="wrapper-se">
        {% for exam in exams %}
        <div class="content-se">
            <div class="card-se">
                <div><h2>{{ exam.name }}</h2></div>
                <div class="row-2">
                    <div><img src="{% static 'Exams/image/view.png' %}" width="30px" alt="Lượt xem"
                              title="Lượt xem"><span> {{ exam.amount_view_user }}</span></div>
                    <div><img src="{% static 'Exams/image/writing.png' %}" width="30px" alt="Lượt làm" title="Lượt làm"><span> {{ exam.amount_do }}</span>
                    </div>
                    <div><img src="{% static 'Exams/image/clock.png' %}" width="30px" alt="Thời gian" title="Thời gian"><span>.  {{ exam.time }} phút</span>
                    </div>
                </div>
                <div>
                    <form action="{% url 'exam:do-exam' exam.slug %}" method="get">
                        {% csrf_token %}
                        <input type="hidden" name="check" value="{{ forloop.counter }}-{{ exam.id }}">
                        <button type="submit">Thi ngay</button>
                    </form>
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if exams.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ exams.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ exams.number }} / {{ exams.paginator.num_pages }}.
        </span>

        {% if exams.has_next %}
            <a href="?page={{ exams.next_page_number }}">next</a>
            <a href="?page={{ exams.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
</div>
{% endblock %}

Exams/templates/Exams/manage.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Exams/css/manage.css' %}">
<div class="wrapper">
    <div>
        <div>Đề đã làm: </div>
        <table class="customers">
            <tr>
                <th>Đề</th>
            </tr>
            {% for exam in exams_do %}
            <tr>
                <td><a href="{% url 'history:show_history' exam.id %}">{{ exam.id_exam.name }}</a></td>

            </tr>
            {% endfor %}
        </table>

    </div>
    <div>
        <div>Đề đã tạo: </div>
        <table class="customers">
            <tr>
                <th>Đề</th>
            </tr>
            {% for exam in exams_create %}
            <tr>
                <td>{{ exam.name }}</td>
            </tr>
            {% endfor %}
        </table>

    </div>
</div>

{% endblock %}

Exams/templates/Exams/score_random.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Exams/css/do_exam.css' %}">
<script src="{% static 'Exams/javascript/do_exam.js' %}"></script>
<div style="color:red; font-size:1.2rem; margin: 20px 0;">Kết quả: {{ score }}\{{ number }}</div>
<div class="wrapper-exam">

    <div class="show-exam">
        <div class="questions">
            {% for question in questions %}
            <div class="question">
                <div class="title-qs">
                    <span>{{ forloop.counter }}. </span>{{ question.question }}
                    <div>
                        {% if question.link_media %}
                        <img src="{{ MEDIA_URL }}{{ question.link_media }}" width="50%">
                        {% endif %}
                    </div>
                </div>

                {% with my_var=forloop.counter %}
                {% for answer in question.answers %}
                {% if answer.label == question.correct_answer and answer.label == question.correct %}
                <div style="color:green;">
                    <span>{{ answer.label }}: </span>
                    <input type="radio" id="{{ my_var }}" name="{{ question.id }}"
                           value="{{ answer.label }}" checked disabled>
                    <label for="{{ my_var }}">{{ answer.content }}</label><br>
                </div>
                {% elif answer.label == question.correct %}
                <div style="color:red;">
                    <span>{{ answer.label }}: </span>
                    <input type="radio" id="{{ my_var }}" name="{{ question.id }}"
                           value="{{ answer.label }}" checked disabled>
                    <label for="{{ my_var }}">{{ answer.content }}</label><br>
                </div>
                {% elif answer.label == question.correct_answer %}
                <div style="color:green;">
                    <span>{{ answer.label }}: </span>
                    <input type="radio" id="{{ my_var }}" name="{{ question.id }}"
                           value="{{ answer.label }}" checked disabled>
                    <label for="{{ my_var }}">{{ answer.content }}</label><br>
                </div>
                {% else %}
                <div>
                    <span>{{ answer.label }}: </span>
                    <input type="radio" id="{{ my_var }}" name="{{ question.id }}"
                           value="{{ answer.label }}" disabled>
                    <label for="{{ my_var }}">{{ answer.content }}</label><br>
                </div>
                {% endif %}

                {% endfor %}
                {% endwith %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Exams/templates/Exams/show_random.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Exams/css/do_exam.css' %}">
<script src="{% static 'Exams/javascript/do_exam.js' %}"></script>
<form action="{% url 'exam:check_random' %}" method="post" id="form-submit">
    {% csrf_token %}
    <input type="hidden" name="do-time" value="{{ time }}" id="do-time">
    <input type="hidden" name="sum" value="{{ sum }}">
    <div class="wrapper-exam">
        <div class="show-exam">
            <div class="questions">
                {% for question in questions %}
                <div class="question">
                    <div class="title-qs">
                        <span>{{ forloop.counter }}. </span>{{ question.question }}
                        <div>
                            {% if question.link_media %}
                            <center><img src="{{ MEDIA_URL }}{{ question.link_media }}" width="50%"></center>
                            {% endif %}
                        </div>
                    </div>
                    {% with my_var=forloop.counter %}


                    {% for answer in question.answers %}
                    <div>
                        <input type="hidden" name="h-{{ my_var }}" value="{{ question.id }}">
                        <span>{{ answer.label }}: </span>
                        <input type="radio" id="{{ my_var }}-{{ question.id }}" name="{{ my_var }}"
                               value="{{ answer.label }}">
                        <label for="{{ my_var }}-{{ question.id }}">{{ answer.content }}</label><br>
                    </div>
                    {% endfor %}
                    {% endwith %}
                </div>
                {% endfor %}
            </div>
            <div class="wrapper-submit">
                <input type="hidden" name="time-do" value="0">
                <button type="submit" class="submit">Nộp bài</button>
            </div>
        </div>
        <div class="check-questions">
            <div id="clock">
                <span id="h">Giờ</span> :
                <span id="m">Phút</span> :
                <span id="s">Giây</span>
            </div>
            <div class="form-check">
                {% for i in questions %}
                <div class="qs qs-{{ forloop.counter }}">{{ forloop.counter }}</div>
                {% endfor %}
            </div>
        </div>

    </div>

</form>
{% endblock %}