Home/urls.py
from django.urls import path
from .views import Index
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Home'
urlpatterns = [
    path('', Index.as_view(), name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyUser/urls.py
from django.urls import path
from .views import Login, Signup, Ajax, Info, Logout, forgotpass
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myuser'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('signup/', Signup.as_view(), name='signup'),
    path('info/', Info.as_view(), name='info'),
    path('forgotpass', forgotpass, name='forgot'),
    path('logout', Logout.as_view(), name='logout'),

    path('ajax/', Ajax.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thiOnline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
    path('dethi/', include('Exams.urls')),
    path('user/', include("MyUser.urls")),
    path('history/', include("History.urls")),
]

MyUser/models.py
# from django.db import models
from djongo import models
from django.contrib.auth.models import AbstractUser
from .validators import validate_file_size


class User(AbstractUser):
    username = models.CharField(max_length=30, unique=False)
    email = models.EmailField(max_length=255, unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    sex = models.CharField(max_length=20, null=False)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    date_of_birth = models.DateTimeField(null=False)
    list_id_exam = models.TextField(null=True, blank=True)
    school = models.TextField(null=False)
    image = models.ImageField(null=True, blank=True, upload_to='user/logo', validators=[validate_file_size], default='user/logo/user.png')
    list_id_history = models.TextField(null=True, blank=True)
    options = models.JSONField(null=True, blank=True, default=dict)

MyUser/forms.py
from django import forms
from .models import User


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'sex', 'phone_number', 'date_of_birth', 'school', 'image', 'password')



    def save(self, commit=True):
        user = super(LoginForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

MyUser/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import LoginForm
from django.http import HttpResponse
from django.contrib import auth
from django.http import JsonResponse
from .checkDataForm import check
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import User
from .serializers import GetAllUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from .tests import reschool


class Login(View):
    def get(self, request):
        f = LoginForm()
        return render(request, 'MyUser/formLogin.html', {'f': f})

    def post(self, request):
        user = auth.authenticate(email=request.POST['email'], password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('exam:show-list-exam')
        else:
            return render(request, 'MyUser/formLogin.html', {'err': 'Email hoặc mật khẩu sai !'})
        

class Signup(View):
    schools = reschool()
    def get(self, request):
        if request.is_ajax():
            return JsonResponse({'data': 'get'}, status=200)
        return render(request, 'MyUser/formSignup.html', {'schools': self.schools})

    def post(self, request):
        f = LoginForm(request.POST, request.FILES)
        if f.is_valid():
            message = check(f)
            if message == "validate":
                f.save()
                return redirect('myuser:login')
            else:
                return HttpResponse(message)
        return HttpResponse(f.errors)


class Ajax(APIView):
    def get(self, request):
        list_user = User.objects.all()
        mydata = GetAllUser(list_user, many=True)
        return Response(data=mydata.data, status=status.HTTP_200_OK)
    
    
class Info(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request):
        return render(request, 'MyUser/info.html')


class Logout(LoginRequiredMixin, View):
    login_url = '/user/login/'

    def get(self, request):
        auth.logout(request)
        return render(request, 'MyUser/formLogin.html')
    


def forgotpass(request):
    send_mail(
        'Subject here',
        'Here is the message.',
        'son1999tmgl@gmail.com',
        ['nguyenxuanson_t62@hus.edu.vn'],
        fail_silently=False,
    )
    return redirect('exam:show-list-exam')

MyUser/templates/MyUser/formLogin.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'MyUser/css/login.css' %}">
<div class="form-login">
    <div class="header-login">LOG IN</div>
    <div style="text-align:center;" class="avatar"><img src="{% static 'MyUser/images/user.png' %}" width="120px" height="120"></div>
    {% if err %}
    <div style="color:red;">{{ err }}</div>
    {% endif %}
    <form action="{% url 'myuser:login' %}" method="post">
        {% csrf_token %}
        <div class="line-form-login">
            <label for="email">email:</label>
            <input type="email" name="email" id="email" placeholder="Email">
        </div>
        <div class="line-form-login">
            <label for="password">Mật khẩu:</label>
            <input type="password" name="password" id="password" placeholder="Mật khẩu">
        </div>
        <div>
            <button type="submit" class="btn-login">Đăng nhập</button>
        </div>
      <div class="forgot-password">
        <a href="{% url 'myuser:forgot' %}">Bạn quên mật khẩu?</a>
      </div>

    </form>
</div>
{% endblock %}

MyUser/templates/MyUser/formSignup.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'MyUser/css/signup.css' %}">
<div class="form-signup">
    <div class="header-signup">SIGN UP</div>
    <div style="text-align:center;" class="avatar"><img src="{% static 'MyUser/images/user.png' %}" width="120px" height="120"></div>
    <form action="{% url 'myuser:signup' %}" method="post" enctype="multipart/form-data" id="form-signup">
        {% csrf_token %}
        <div class="line-form-signup">
            <label for="username">Họ tên:</label>
            <input type="text" name="username" id="username" placeholder="Họ và tên">
        </div>
        <div class="line-form-signup">
            <label for="email">email:</label>
            <input type="email" name="email" id="email" placeholder="Email">
        </div>
        <div class="line-form-signup">
            <label for="password">Mật khẩu:</label>
            <input type="password" name="password" id="password" placeholder="Mật khẩu">
        </div>
        <div class="line-form-signup inline3">
            <div>
                <label for="phone">SĐT:</label>
                <input type="text" name="phone_number" id="phone_number" placeholder="Điện thoại" id="phone">
            </div>
            <div>
                <label for="sex">Giới tính:</label>
                <select name="sex" id="sex">
                    <option value="Nam">Nam</option>
                    <option value="Nữ">Nữ</option>
                </select>
            </div>
            <div>
                <label for="date_of_birth">Ngày sinh: </label>
                <input type="date" name="date_of_birth" id="date_of_birth">
            </div>
        </div>

        <div class="line-form-signup inline3">
            <div>
                <label for="truong">Trường:</label>
                <select name="school" id="truong">
                    {% for school in schools %}
                         <option value="{{ school }}">{{ school }}</option>
                    {% endfor %}
                </select>
            </div>

        </div>
        <div class="line-form-signup">
            <label for="images">Avatar:</label>
            <span><input type="file" name="image" accept="image/png, image/gif, image/jpeg" id="images"></span>
        </div>
        <div>
            <button type="submit" class="btn-signup">Đăng ký</button>
        </div>
    </form>
</div>
<script src="{% static 'MyUser/javascript/loadAjax.js' %}"></script>
{% endblock %}

MyUser/templates/MyUser/info.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'MyUser/css/info.css' %}">
<div class="info">
  <form>
    <div class="img-avatar">
      <img src="{{ MEDIA_URL }}{{ user.image }}">
    </div>
    <div>
      <label for="name">Họ tên: </label>
      <input type="text" id="name" value="{{ user.username }}">
    </div>
    <div>
      <label for="email">Email: </label>
      <input type="email" id="email" value="{{ user.email }}">
    </div>
    <div>
      <label for="sex">Giới tính: </label>
      <input type="text" id="sex" value="{{ user.sex }}">
    </div>
    <div>
      <label for="phone_number">Điện thoại: </label>
      <input type="phone" id="phone_number" value="{{ user.phone_number }}">
    </div>
    <div>
      <label for="date_of_birth">Ngày sinh: </label>
      <input type="text" id="date_of_birth" value="{{ user.date_of_birth }}">
    </div>
    <div>
      <label for="school">Trường: </label>
      <input type="text" id="school" value="{{ user.school }}">
    </div>

  </form>
</div>


<div class="logout"><a href="{% url 'myuser:logout' %}">Logout</a></div>
{% endblock %}